# Generated by Django 5.2.4 on 2025-07-04 01:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialpage',
            name='description',
        ),
        migrations.AddField(
            model_name='testimonialpage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the person giving the testimonial', 'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Age of the person giving the testimonial'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Position of the person giving the testimonial', 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'The testimonial text', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('testimony_name', 0), ('testimony_age', 1), ('testimony_position', 2), ('testimonial_context', 3)]], {})}, default=list),
        ),
    ]
