# Generated by Django 5.2.4 on 2025-07-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_text',
            field=models.TextField(blank=True),
        ),
    ]
