# Generated by Django 5.2.4 on 2025-07-04 01:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguidepage',
            name='guides',
            field=wagtail.fields.StreamField([('guide', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for the guide', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('guide_title', 0), ('guide_context', 1), ('guide_image', 2)]], {})}, default=list),
        ),
    ]
